/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Fragment Hashtags Management Domain Models
 */

/**
 * https://bitbucket.org/goodai/cosphere-fragment-service/src/b023ad5da15027683028609c140260b0a1808452/cosphere_fragment_service/hashtag/views.py/#lines-29
 */

export interface BulkReadFragmentHashtagsQuery {
    first_character?: string;
    limit?: number;
    offset?: number;
}

/**
 * https://bitbucket.org/goodai/cosphere-fragment-service/src/b023ad5da15027683028609c140260b0a1808452/cosphere_fragment_service/hashtag/serializers.py/#lines-33
 */

export interface BulkReadFragmentHashtagsResponseEntity {
    count: number;
    id?: number;
    text: string;
}

export interface BulkReadFragmentHashtagsResponse {
    data: BulkReadFragmentHashtagsResponseEntity[];
}

/**
 * https://bitbucket.org/goodai/cosphere-fragment-service/src/b023ad5da15027683028609c140260b0a1808452/cosphere_fragment_service/hashtag/views.py/#lines-29
 */

export interface BulkReadPublishedFragmentHashtagsQuery {
    first_character?: string;
    limit?: number;
    offset?: number;
}

/**
 * https://bitbucket.org/goodai/cosphere-fragment-service/src/b023ad5da15027683028609c140260b0a1808452/cosphere_fragment_service/hashtag/serializers.py/#lines-33
 */

export interface BulkReadPublishedFragmentHashtagsResponseEntity {
    count: number;
    id?: number;
    text: string;
}

export interface BulkReadPublishedFragmentHashtagsResponse {
    data: BulkReadPublishedFragmentHashtagsResponseEntity[];
}