/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Fragment Words Management Domain Examples
 */

/**
 * Examples for BULK_READ_FRAGMENT_WORDS
 */
export const BulkReadFragmentWordsExamples = {
    
}

/**
 * Examples for BULK_READ_PUBLISHED_FRAGMENT_WORDS
 */
export const BulkReadPublishedFragmentWordsExamples = {
    
}