/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Recall Management Domain Examples
 */

/**
 * Examples for CREATE_RECALL_SESSION
 */
export const CreateRecallSessionExamples = {
    
}

/**
 * Examples for READ_RECALL_SUMMARY
 */
export const ReadRecallSummaryExamples = {
    
}