/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Payments Management Domain Examples
 */

/**
 * Examples for UPDATE_PAYMENT_STATUS
 */
export const UpdatePaymentStatusExamples = {
    
}