/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Paths Management Domain Examples
 */

/**
 * Examples for BULK_DELETE_PATHS
 */
export const BulkDeletePathsExamples = {
    
}

/**
 * Examples for BULK_READ_PATHS
 */
export const BulkReadPathsExamples = {
    
}

/**
 * Examples for CREATE_PATH
 */
export const CreatePathExamples = {
    
}

/**
 * Examples for READ_PATH
 */
export const ReadPathExamples = {
    
}

/**
 * Examples for UPDATE_PATH
 */
export const UpdatePathExamples = {
    
}