/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Nouns Management Domain
 */
import { Injectable } from '@angular/core';
import { filter } from 'rxjs/operators';
import { Observable } from 'rxjs';
import * as _ from 'underscore';

import { ClientService } from '../../services/client.service';
import { DataState } from '../../services/client.interface';

import * as X from './nouns.models';

@Injectable()
export class NounsDomain {
    constructor(private client: ClientService) {}

    /**
     * Bulk Read Noun Project Icons
     */
    public bulkReadIcons(params: X.BulkReadIconsQuery): DataState<X.BulkReadIconsResponseEntity[]> {
        return this.client.getDataState<X.BulkReadIconsResponseEntity[]>('/nouns/', { params, responseMap: 'icons', authorizationRequired: true });
    }
    
    public bulkReadIcons2(params: X.BulkReadIconsQuery): Observable<X.BulkReadIconsResponseEntity[]> {
        return this.client.get<X.BulkReadIconsResponseEntity[]>('/nouns/', { params, responseMap: 'icons', authorizationRequired: true });
    }

}