/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Nouns Management Domain Models
 */

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/cosphere_media_service/noun/views.py/#lines-26
 */

export interface BulkReadIconsQuery {
    limit?: number;
    offset?: number;
    query: string;
}

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/cosphere_media_service/noun/client.py/#lines-20
 */

export interface BulkReadIconsResponseEntity {
    download_url: string;
    preview_url: string;
}

export interface BulkReadIconsResponse {
    icons: BulkReadIconsResponseEntity[];
}