/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Nouns Management Domain Examples
 */

/**
 * Examples for BULK_READ_ICONS
 */
export const BulkReadIconsExamples = {
    "200 (ICONS_BULK_READ)": {
        "content": {
            "@event": "ICONS_BULK_READ",
            "@type": "icons_list",
            "icons": []
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "400 (QUERY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "QUERY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "query": [
                    "This field is required."
                ]
            },
            "user_id": 890
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "500 (PROBLEMS_WHEN_BULK_READING_ICONS_DETECTED)": {
        "content": {
            "@event": "PROBLEMS_WHEN_BULK_READING_ICONS_DETECTED",
            "@type": "error",
            "limit": 50,
            "offset": 0,
            "query": "tirikam",
            "user_id": null
        },
        "content_type": "application/json",
        "status": 500
    }
}