/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Internal Management Domain Examples
 */

/**
 * Examples for DELETE_ENTRIES_FOR_USER
 */
export const DeleteEntriesForUserExamples = {
    
}