/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Bricks Management Domain Examples
 */

/**
 * Examples for BULK_READ_GAMEATTEMPTS
 */
export const BulkReadGameattemptsExamples = {
    "200 (GAMEATTEMPTS_BULK_READ)": {
        "content": {
            "@event": "GAMEATTEMPTS_BULK_READ",
            "@type": "game_attempts_list",
            "attempts": [
                {
                    "@type": "game_attempt",
                    "attempt": [
                        {
                            "brick_id": 0,
                            "category_id": 11
                        },
                        {
                            "brick_id": 1,
                            "category_id": 13
                        }
                    ],
                    "created_timestamp": 1533997561.495856,
                    "game_id": 25,
                    "id": 7,
                    "start_timestamp": 1533997561.494029,
                    "user_id": 190
                },
                {
                    "@type": "game_attempt",
                    "attempt": [
                        {
                            "brick_id": 0,
                            "category_id": 11
                        },
                        {
                            "brick_id": 1,
                            "category_id": 13
                        }
                    ],
                    "created_timestamp": 1533997561.498041,
                    "game_id": 25,
                    "id": 8,
                    "start_timestamp": 1533997561.496314,
                    "user_id": 190
                }
            ]
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "400 (RESPONSE_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "RESPONSE_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "game_attempts": [
                    "This field is required."
                ]
            },
            "user_id": 191
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (COULD_NOT_FIND_GAME)": {
        "content": {
            "@event": "COULD_NOT_FIND_GAME",
            "@type": "error",
            "user_id": 191
        },
        "content_type": "application/json",
        "status": 404
    }
}

/**
 * Examples for BULK_READ_GAMES
 */
export const BulkReadGamesExamples = {
    "200 (GAMES_BULK_READ)": {
        "content": {
            "@event": "GAMES_BULK_READ",
            "@type": "games_list",
            "games": []
        },
        "content_type": "application/json",
        "status": 200
    }
}

/**
 * Examples for CREATE_GAME
 */
export const CreateGameExamples = {
    "201 (GAME_CREATED)": {
        "content": {
            "@event": "GAME_CREATED",
            "@type": "game",
            "bricks": [
                {
                    "background": null,
                    "category_cid": 0,
                    "category_id": 0,
                    "cid": 0,
                    "falling_time": 10000,
                    "foreground": {
                        "image_uri": null,
                        "language": "en",
                        "text": "hi"
                    },
                    "id": 0,
                    "reason": null
                },
                {
                    "background": null,
                    "category_cid": 1,
                    "category_id": 1,
                    "cid": 1,
                    "falling_time": 10000,
                    "foreground": {
                        "image_uri": null,
                        "language": "en",
                        "text": "hi"
                    },
                    "id": 1,
                    "reason": null
                }
            ],
            "categories": [
                {
                    "cid": 0,
                    "id": 0,
                    "text": "hi"
                },
                {
                    "cid": 1,
                    "id": 1,
                    "text": "ho"
                }
            ],
            "challenge": "your clothes",
            "id": 15,
            "terms": [
                "smile",
                "clothes",
                "hold",
                "Jon"
            ],
            "title": "hello Jon smile hold",
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 201
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "bricks": [
                    {
                        "cid": [
                            "A valid integer is required."
                        ]
                    }
                ]
            },
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "500 (GENERIC_ERROR_OCCURRED)": {
        "content": {
            "@event": "GENERIC_ERROR_OCCURRED",
            "@type": "error",
            "errors": [
                "{'__all__': ['each category must have a least one brick']}"
            ],
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 500
    }
}

/**
 * Examples for CREATE_GAMEATTEMPT
 */
export const CreateGameattemptExamples = {
    "201 (GAMEATTEMPT_CREATED)": {
        "content": {
            "@event": "GAMEATTEMPT_CREATED",
            "@type": "game_attempt",
            "attempt": [
                {
                    "brick_id": 13,
                    "category_id": 14
                },
                {
                    "brick_id": 14,
                    "category_id": 15
                }
            ],
            "created_timestamp": 1533997561.543092,
            "game_id": 28,
            "id": 11,
            "start_timestamp": 1542285101.0,
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 201
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "attempt": [
                    {
                        "brick_id": [
                            "This field is required."
                        ]
                    },
                    {
                        "category_id": [
                            "This field is required."
                        ]
                    }
                ]
            },
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (COULD_NOT_FIND_GAME)": {
        "content": {
            "@event": "COULD_NOT_FIND_GAME",
            "@type": "error",
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 404
    },
    
    "500 (GENERIC_ERROR_OCCURRED)": {
        "content": {
            "@event": "GENERIC_ERROR_OCCURRED",
            "@type": "error",
            "errors": [
                "{'start_datetime': ['This field cannot be null.']}"
            ],
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 500
    }
}

/**
 * Examples for DELETE_GAME
 */
export const DeleteGameExamples = {
    "200 (GAME_DELETED)": {
        "content": {
            "@event": "GAME_DELETED",
            "@type": "empty"
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "400 (GAME_WITH_ATTEMPTS_DETECTED)": {
        "content": {
            "@event": "GAME_WITH_ATTEMPTS_DETECTED",
            "@type": "error",
            "user_id": null
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (COULD_NOT_FIND_GAME)": {
        "content": {
            "@event": "COULD_NOT_FIND_GAME",
            "@type": "error",
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 404
    },
    
    "500 (GENERIC_ERROR_OCCURRED)": {
        "content": {
            "@event": "GENERIC_ERROR_OCCURRED",
            "@type": "error",
            "errors": [
                "Unsupported lookup 'neq' for BigIntegerField or join on the field not permitted."
            ],
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 500
    }
}

/**
 * Examples for READ_GAME
 */
export const ReadGameExamples = {
    "200 (GAME_READ)": {
        "content": {
            "@event": "GAME_READ",
            "@type": "game",
            "bricks": [
                {
                    "background": {
                        "audio_language": "en",
                        "audio_text": "Money material commercial role any also executive physical.",
                        "audio_uri": null
                    },
                    "category_id": 3,
                    "falling_time": 1600,
                    "id": 4,
                    "reason": "Whatever day prepare bill response."
                },
                {
                    "category_id": 4,
                    "falling_time": 1600,
                    "foreground": {
                        "image_uri": null,
                        "language": "en",
                        "text": "Exist which method laugh."
                    },
                    "id": 5,
                    "reason": "Break Democrat necessary civil exist."
                }
            ],
            "categories": [
                {
                    "cid": 11,
                    "id": 3,
                    "text": "true"
                },
                {
                    "cid": 12,
                    "id": 4,
                    "text": "false"
                }
            ],
            "challenge": "Various set property case.",
            "id": 20,
            "terms": [
                "staff",
                "plan"
            ],
            "title": "Perform interview say money agent.",
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "404 (COULD_NOT_FIND_GAME)": {
        "content": {
            "@event": "COULD_NOT_FIND_GAME",
            "@type": "error",
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 404
    }
}

/**
 * Examples for UPDATE_GAME
 */
export const UpdateGameExamples = {
    "200 (GAME_UPDATED)": {
        "content": {
            "@event": "GAME_UPDATED",
            "@type": "game",
            "bricks": [
                {
                    "background": null,
                    "category_cid": 0,
                    "category_id": 0,
                    "cid": 0,
                    "falling_time": 10000,
                    "foreground": {
                        "image_uri": null,
                        "language": "en",
                        "text": "hi"
                    },
                    "id": 11,
                    "reason": null
                },
                {
                    "background": null,
                    "category_cid": 1,
                    "category_id": 1,
                    "cid": 0,
                    "falling_time": 10000,
                    "foreground": {
                        "image_uri": null,
                        "language": "en",
                        "text": "hi"
                    },
                    "id": 12,
                    "reason": null
                }
            ],
            "categories": [
                {
                    "cid": 0,
                    "id": 0,
                    "text": "hi"
                },
                {
                    "cid": 1,
                    "id": 1,
                    "text": "ho"
                }
            ],
            "challenge": "your clothes",
            "id": 22,
            "terms": [
                "smile",
                "clothes",
                "hold",
                "Jon"
            ],
            "title": "hello Jon smile hold",
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "non_field_errors": [
                    "one cannot have less then 2 categories"
                ]
            },
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "400 (GAME_WITH_ATTEMPTS_DETECTED)": {
        "content": {
            "@event": "GAME_WITH_ATTEMPTS_DETECTED",
            "@type": "error",
            "user_id": null
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (COULD_NOT_FIND_GAME)": {
        "content": {
            "@event": "COULD_NOT_FIND_GAME",
            "@type": "error",
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 404
    },
    
    "500 (GENERIC_ERROR_OCCURRED)": {
        "content": {
            "@event": "GENERIC_ERROR_OCCURRED",
            "@type": "error",
            "errors": [
                "{'__all__': ['each category must have a least one brick']}"
            ],
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 500
    }
}