/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Bricks Management Domain Models
 */

/**
 * https://bitbucket.org/goodai/cosphere-app-bricks-be/src/9dfe86168ecc1beac0ce22a6ba200163f317fdba/cosphere_app_bricks_be/game/serializers.py/#lines-71
 */

export interface BulkReadGameattemptsResponseEntity {
    attempt?: Object;
    created_timestamp: number;
    game_id?: any;
    id?: number;
    start_timestamp: number;
    user_id: number;
}

export interface BulkReadGameattemptsResponse {
    attempts: BulkReadGameattemptsResponseEntity[];
}

/**
 * https://bitbucket.org/goodai/cosphere-app-bricks-be/src/9dfe86168ecc1beac0ce22a6ba200163f317fdba/cosphere_app_bricks_be/game/serializers.py/#lines-25
 */

export interface BulkReadGamesResponseEntity {
    bricks: Object;
    categories: Object;
    challenge?: string;
    id?: number;
    terms: Object;
    title: string;
    user_id: number;
}

export interface BulkReadGamesResponse {
    games: BulkReadGamesResponseEntity[];
}

/**
 * https://bitbucket.org/goodai/cosphere-app-bricks-be/src/9dfe86168ecc1beac0ce22a6ba200163f317fdba/cosphere_app_bricks_be/game/parsers.py/#lines-54
 */

export enum CreateGameBodyAudioLanguage {
    cy = 'cy',
    da = 'da',
    de = 'de',
    en = 'en',
    es = 'es',
    fr = 'fr',
    is = 'is',
    it = 'it',
    ja = 'ja',
    ko = 'ko',
    nb = 'nb',
    nl = 'nl',
    pl = 'pl',
    pt = 'pt',
    ro = 'ro',
    ru = 'ru',
    sv = 'sv',
    tr = 'tr',
}

export enum CreateGameBodyLanguage {
    af = 'af',
    am = 'am',
    an = 'an',
    ar = 'ar',
    as = 'as',
    az = 'az',
    be = 'be',
    bg = 'bg',
    bn = 'bn',
    br = 'br',
    bs = 'bs',
    ca = 'ca',
    cs = 'cs',
    cy = 'cy',
    da = 'da',
    de = 'de',
    dz = 'dz',
    el = 'el',
    en = 'en',
    eo = 'eo',
    es = 'es',
    et = 'et',
    eu = 'eu',
    fa = 'fa',
    fi = 'fi',
    fo = 'fo',
    fr = 'fr',
    ga = 'ga',
    gl = 'gl',
    gu = 'gu',
    he = 'he',
    hi = 'hi',
    hr = 'hr',
    ht = 'ht',
    hu = 'hu',
    hy = 'hy',
    id = 'id',
    is = 'is',
    it = 'it',
    ja = 'ja',
    jv = 'jv',
    ka = 'ka',
    kk = 'kk',
    km = 'km',
    kn = 'kn',
    ko = 'ko',
    ku = 'ku',
    ky = 'ky',
    la = 'la',
    lb = 'lb',
    lo = 'lo',
    lt = 'lt',
    lv = 'lv',
    mg = 'mg',
    mk = 'mk',
    ml = 'ml',
    mn = 'mn',
    mr = 'mr',
    ms = 'ms',
    mt = 'mt',
    nb = 'nb',
    ne = 'ne',
    nl = 'nl',
    nn = 'nn',
    no = 'no',
    oc = 'oc',
    or = 'or',
    pa = 'pa',
    pl = 'pl',
    ps = 'ps',
    pt = 'pt',
    qu = 'qu',
    ro = 'ro',
    ru = 'ru',
    rw = 'rw',
    se = 'se',
    si = 'si',
    sk = 'sk',
    sl = 'sl',
    sq = 'sq',
    sr = 'sr',
    sv = 'sv',
    sw = 'sw',
    ta = 'ta',
    te = 'te',
    th = 'th',
    tl = 'tl',
    tr = 'tr',
    ug = 'ug',
    uk = 'uk',
    ur = 'ur',
    vi = 'vi',
    vo = 'vo',
    wa = 'wa',
    xh = 'xh',
    zh = 'zh',
    zu = 'zu',
}

export interface CreateGameBody {
    bricks: {
        background?: {
            audio_language?: CreateGameBodyAudioLanguage;
            audio_text?: string;
            audio_uri?: string;
        };
        category_cid: number;
        category_id?: number;
        cid: number;
        foreground?: {
            image_uri?: string;
            language?: CreateGameBodyLanguage;
            text?: string;
        };
        id?: number;
        reason?: string;
    }[];
    categories: {
        cid: number;
        id?: number;
        text: string;
    }[];
    challenge: string;
    title: string;
}

/**
 * https://bitbucket.org/goodai/cosphere-app-bricks-be/src/9dfe86168ecc1beac0ce22a6ba200163f317fdba/cosphere_app_bricks_be/game/serializers.py/#lines-7
 */

export interface CreateGameResponse {
    bricks: Object;
    categories: Object;
    challenge?: string;
    id?: number;
    terms: Object;
    title: string;
    user_id: number;
}

/**
 * https://bitbucket.org/goodai/cosphere-app-bricks-be/src/9dfe86168ecc1beac0ce22a6ba200163f317fdba/cosphere_app_bricks_be/game/parsers.py/#lines-72
 */

export interface CreateGameattemptBody {
    attempt: {
        brick_id: number;
        category_id: number;
    }[];
    start_datetime: string;
}

/**
 * https://bitbucket.org/goodai/cosphere-app-bricks-be/src/9dfe86168ecc1beac0ce22a6ba200163f317fdba/cosphere_app_bricks_be/game/serializers.py/#lines-41
 */

export interface CreateGameattemptResponse {
    attempt?: Object;
    created_timestamp: number;
    game_id?: any;
    id?: number;
    start_timestamp: number;
    user_id: number;
}

/**
 * https://bitbucket.org/goodai/cosphere-app-bricks-be/src/9dfe86168ecc1beac0ce22a6ba200163f317fdba/.venv/src/lily/lily/base/serializers.py/#lines-158
 */

export interface DeleteGameResponse {}

/**
 * https://bitbucket.org/goodai/cosphere-app-bricks-be/src/9dfe86168ecc1beac0ce22a6ba200163f317fdba/cosphere_app_bricks_be/game/serializers.py/#lines-7
 */

export interface ReadGameResponse {
    bricks: Object;
    categories: Object;
    challenge?: string;
    id?: number;
    terms: Object;
    title: string;
    user_id: number;
}

/**
 * https://bitbucket.org/goodai/cosphere-app-bricks-be/src/9dfe86168ecc1beac0ce22a6ba200163f317fdba/cosphere_app_bricks_be/game/parsers.py/#lines-54
 */

export enum UpdateGameBodyAudioLanguage {
    cy = 'cy',
    da = 'da',
    de = 'de',
    en = 'en',
    es = 'es',
    fr = 'fr',
    is = 'is',
    it = 'it',
    ja = 'ja',
    ko = 'ko',
    nb = 'nb',
    nl = 'nl',
    pl = 'pl',
    pt = 'pt',
    ro = 'ro',
    ru = 'ru',
    sv = 'sv',
    tr = 'tr',
}

export enum UpdateGameBodyLanguage {
    af = 'af',
    am = 'am',
    an = 'an',
    ar = 'ar',
    as = 'as',
    az = 'az',
    be = 'be',
    bg = 'bg',
    bn = 'bn',
    br = 'br',
    bs = 'bs',
    ca = 'ca',
    cs = 'cs',
    cy = 'cy',
    da = 'da',
    de = 'de',
    dz = 'dz',
    el = 'el',
    en = 'en',
    eo = 'eo',
    es = 'es',
    et = 'et',
    eu = 'eu',
    fa = 'fa',
    fi = 'fi',
    fo = 'fo',
    fr = 'fr',
    ga = 'ga',
    gl = 'gl',
    gu = 'gu',
    he = 'he',
    hi = 'hi',
    hr = 'hr',
    ht = 'ht',
    hu = 'hu',
    hy = 'hy',
    id = 'id',
    is = 'is',
    it = 'it',
    ja = 'ja',
    jv = 'jv',
    ka = 'ka',
    kk = 'kk',
    km = 'km',
    kn = 'kn',
    ko = 'ko',
    ku = 'ku',
    ky = 'ky',
    la = 'la',
    lb = 'lb',
    lo = 'lo',
    lt = 'lt',
    lv = 'lv',
    mg = 'mg',
    mk = 'mk',
    ml = 'ml',
    mn = 'mn',
    mr = 'mr',
    ms = 'ms',
    mt = 'mt',
    nb = 'nb',
    ne = 'ne',
    nl = 'nl',
    nn = 'nn',
    no = 'no',
    oc = 'oc',
    or = 'or',
    pa = 'pa',
    pl = 'pl',
    ps = 'ps',
    pt = 'pt',
    qu = 'qu',
    ro = 'ro',
    ru = 'ru',
    rw = 'rw',
    se = 'se',
    si = 'si',
    sk = 'sk',
    sl = 'sl',
    sq = 'sq',
    sr = 'sr',
    sv = 'sv',
    sw = 'sw',
    ta = 'ta',
    te = 'te',
    th = 'th',
    tl = 'tl',
    tr = 'tr',
    ug = 'ug',
    uk = 'uk',
    ur = 'ur',
    vi = 'vi',
    vo = 'vo',
    wa = 'wa',
    xh = 'xh',
    zh = 'zh',
    zu = 'zu',
}

export interface UpdateGameBody {
    bricks: {
        background?: {
            audio_language?: UpdateGameBodyAudioLanguage;
            audio_text?: string;
            audio_uri?: string;
        };
        category_cid: number;
        category_id?: number;
        cid: number;
        foreground?: {
            image_uri?: string;
            language?: UpdateGameBodyLanguage;
            text?: string;
        };
        id?: number;
        reason?: string;
    }[];
    categories: {
        cid: number;
        id?: number;
        text: string;
    }[];
    challenge: string;
    title: string;
}

/**
 * https://bitbucket.org/goodai/cosphere-app-bricks-be/src/9dfe86168ecc1beac0ce22a6ba200163f317fdba/cosphere_app_bricks_be/game/serializers.py/#lines-7
 */

export interface UpdateGameResponse {
    bricks: Object;
    categories: Object;
    challenge?: string;
    id?: number;
    terms: Object;
    title: string;
    user_id: number;
}