/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Geometries Management Domain Examples
 */

/**
 * Examples for BULK_READ_GEOMETRIES
 */
export const BulkReadGeometriesExamples = {
    
}

/**
 * Examples for BULK_UPDATE_GEOMETRIES
 */
export const BulkUpdateGeometriesExamples = {
    
}

/**
 * Examples for READ_GEOMETRY_BY_CARD
 */
export const ReadGeometryByCardExamples = {
    
}

/**
 * Examples for READ_GRAPH
 */
export const ReadGraphExamples = {
    
}