/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Notification Management Domain Examples
 */

/**
 * Examples for ACKNOWLEDGE_NOTIFICATION
 */
export const AcknowledgeNotificationExamples = {
    "200 (NOTIFICATION_ACKNOWLEDGED)": {
        "content": {
            "@event": "NOTIFICATION_ACKNOWLEDGED",
            "@type": "empty"
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "404 (COULD_NOT_FIND_NOTIFICATION)": {
        "content": {
            "@event": "COULD_NOT_FIND_NOTIFICATION",
            "@type": "error",
            "user_id": 11
        },
        "content_type": "application/json",
        "status": 404
    }
}

/**
 * Examples for BULK_READ_NOTIFICATIONS
 */
export const BulkReadNotificationsExamples = {
    "200 (NOTIFICATIONS_BULK_READ)": {
        "content": {
            "@event": "NOTIFICATIONS_BULK_READ",
            "@type": "notifications_list",
            "notifications": []
        },
        "content_type": "application/json",
        "status": 200
    }
}