/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Account Settings Management Domain Examples
 */

/**
 * Examples for READ_ACCOUNTSETTING
 */
export const ReadAccountsettingExamples = {
    
}

/**
 * Examples for UPDATE_ACCOUNTSETTING
 */
export const UpdateAccountsettingExamples = {
    
}