/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Account Settings Management Domain Models
 */

/**
 * https://bitbucket.org/goodai/cosphere-auth-service/src/09d74e1c1f6871739268cd74315b4f114592af2c/cosphere_auth_service/account_setting/serializers.py/#lines-8
 */

export interface ReadAccountsettingResponse {
    help_freq?: number;
    help_view_last_seen?: Object;
    lang?: string;
    recaller_breaker_value?: number;
    recaller_timer_value?: number;
}

/**
 * https://bitbucket.org/goodai/cosphere-auth-service/src/09d74e1c1f6871739268cd74315b4f114592af2c/cosphere_auth_service/account_setting/views.py/#lines-17
 */

export interface UpdateAccountsettingBody {
    help_freq?: number;
    help_view_last_seen?: Object;
    lang?: string;
    recaller_breaker_value?: number;
    recaller_timer_value?: number;
}

/**
 * https://bitbucket.org/goodai/cosphere-auth-service/src/09d74e1c1f6871739268cd74315b4f114592af2c/cosphere_auth_service/account_setting/serializers.py/#lines-8
 */

export interface UpdateAccountsettingResponse {
    help_freq?: number;
    help_view_last_seen?: Object;
    lang?: string;
    recaller_breaker_value?: number;
    recaller_timer_value?: number;
}