/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Account Settings Management Domain
 */
import { Injectable } from '@angular/core';
import { filter } from 'rxjs/operators';
import { Observable } from 'rxjs';
import * as _ from 'underscore';

import { ClientService } from '../../services/client.service';
import { DataState } from '../../services/client.interface';

import * as X from './account_settings.models';

@Injectable()
export class AccountSettingsDomain {
    constructor(private client: ClientService) {}

    /**
     * Read Account Settings
     */
    public readAccountsetting(): DataState<X.ReadAccountsettingResponse> {
        return this.client.getDataState<X.ReadAccountsettingResponse>('/account/settings/', { authorizationRequired: true });
    }

    /**
     * Update Account Settings
     */
    public updateAccountsetting(body: X.UpdateAccountsettingBody): Observable<X.UpdateAccountsettingResponse> {
        return this.client
            .put<X.UpdateAccountsettingResponse>('/account/settings/', body, { authorizationRequired: true })
            .pipe(filter(x => !_.isEmpty(x)));
    }

}