/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Categories Management Domain Models
 */

/**
 * https://bitbucket.org/goodai/cosphere-entity-service/src/5f215fabba7fa3925151c098fad0051162452821/cosphere_entity_service/category/serializers.py/#lines-27
 */

export enum BulkReadCategoriesResponseText {
    FORGOTTEN = 'FORGOTTEN',
    HOT = 'HOT',
    NOT_RECALLED = 'NOT_RECALLED',
    PROBLEMATIC = 'PROBLEMATIC',
    RECENTLY_ADDED = 'RECENTLY_ADDED',
}

export interface BulkReadCategoriesResponseEntity {
    count: number;
    id?: number;
    text: BulkReadCategoriesResponseText;
}

export interface BulkReadCategoriesResponse {
    categories: BulkReadCategoriesResponseEntity[];
}