/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Fragment Hashtags Management Domain Examples
 */

/**
 * Examples for BULK_READ_FRAGMENT_HASHTAGS
 */
export const BulkReadFragmentHashtagsExamples = {
    
}

/**
 * Examples for BULK_READ_PUBLISHED_FRAGMENT_HASHTAGS
 */
export const BulkReadPublishedFragmentHashtagsExamples = {
    
}