/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Payment Cards Management Domain Examples
 */

/**
 * Examples for AS_DEFAULT_MARK_PAYMENTCARD
 */
export const AsDefaultMarkPaymentcardExamples = {
    "200 (PAYMENTCARD_AS_DEFAULT_MARKED)": {
        "content": {
            "@event": "PAYMENTCARD_AS_DEFAULT_MARKED",
            "@type": "empty"
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "404 (COULD_NOT_FIND_PAYMENTCARD)": {
        "content": {
            "@event": "COULD_NOT_FIND_PAYMENTCARD",
            "@type": "error",
            "user_id": 464
        },
        "content_type": "application/json",
        "status": 404
    }
}

/**
 * Examples for BULK_READ_PAYMENTCARDS
 */
export const BulkReadPaymentcardsExamples = {
    "200 (PAYMENTCARDS_BULK_READ)": {
        "content": {
            "@event": "PAYMENTCARDS_BULK_READ",
            "@type": "payment_cards_list",
            "payment_cards": [
                {
                    "@type": "payment_card",
                    "expiration_month": 9,
                    "expiration_year": 2016,
                    "expired": true,
                    "id": 28,
                    "is_default": false,
                    "is_fully_defined": true,
                    "masked_number": "444433******2222",
                    "payments": [
                        {
                            "@type": "payment",
                            "amount": "145",
                            "created_timestamp": 1512213241.0,
                            "display_amount": "1.45",
                            "product": {
                                "@type": "product",
                                "currency": "PLN",
                                "display_price": "29.90",
                                "name": "Miesi\u0119czna Subskrypcja Learner w CoSphere.org",
                                "price": "2990",
                                "product_type": "SUBSCRIPTION_LEARNER_MONTHLY"
                            },
                            "status": "PENDING",
                            "status_ledger": null
                        }
                    ]
                },
                {
                    "@type": "payment_card",
                    "expiration_month": 12,
                    "expiration_year": 2017,
                    "expired": false,
                    "id": 27,
                    "is_default": false,
                    "is_fully_defined": true,
                    "masked_number": "444433******1111",
                    "payments": [
                        {
                            "@type": "payment",
                            "amount": "154",
                            "created_timestamp": 1511349241.0,
                            "display_amount": "1.54",
                            "product": {
                                "@type": "product",
                                "currency": "PLN",
                                "display_price": "29.90",
                                "name": "Miesi\u0119czna Subskrypcja Learner w CoSphere.org",
                                "price": "2990",
                                "product_type": "SUBSCRIPTION_LEARNER_MONTHLY"
                            },
                            "status": "PENDING",
                            "status_ledger": null
                        },
                        {
                            "@type": "payment",
                            "amount": "93",
                            "created_timestamp": 1510744441.0,
                            "display_amount": "0.93",
                            "product": {
                                "@type": "product",
                                "currency": "PLN",
                                "display_price": null,
                                "name": "Dotacja CoSphere.org",
                                "price": null,
                                "product_type": "DONATION"
                            },
                            "status": "PENDING",
                            "status_ledger": null
                        }
                    ]
                }
            ]
        },
        "content_type": "application/json",
        "status": 200
    }
}

/**
 * Examples for CREATE_PAYMENTCARD
 */
export const CreatePaymentcardExamples = {
    "201 (PAYMENTCARD_CREATED)": {
        "content": {
            "@event": "PAYMENTCARD_CREATED",
            "@type": "payment_card",
            "expiration_month": 7,
            "expiration_year": 2019,
            "expired": false,
            "id": 32,
            "is_default": true,
            "is_fully_defined": false,
            "masked_number": "6789*****34556",
            "payments": []
        },
        "content_type": "application/json",
        "status": 201
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "token": [
                    "This field is required."
                ]
            },
            "user_id": 472
        },
        "content_type": "application/json",
        "status": 400
    }
}

/**
 * Examples for DELETE_PAYMENTCARD
 */
export const DeletePaymentcardExamples = {
    "200 (PAYMENTCARD_DELETED)": {
        "content": {
            "@event": "PAYMENTCARD_DELETED",
            "@type": "empty"
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "400 (COULD_NOT_REMOVE_DEFAULT_PAYMENT_CARD)": {
        "content": {
            "@event": "COULD_NOT_REMOVE_DEFAULT_PAYMENT_CARD",
            "@type": "error",
            "payment_card_id": "89",
            "user_id": 476
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (COULD_NOT_FIND_PAYMENTCARD)": {
        "content": {
            "@event": "COULD_NOT_FIND_PAYMENTCARD",
            "@type": "error",
            "user_id": 480
        },
        "content_type": "application/json",
        "status": 404
    }
}

/**
 * Examples for PAY_WITH_DEFAULT_PAYMENT_CARD
 */
export const PayWithDefaultPaymentCardExamples = {
    "200 (WITH_DEFAULT_PAYMENT_CARD_PAID)": {
        "content": {
            "@event": "WITH_DEFAULT_PAYMENT_CARD_PAID",
            "@type": "payment",
            "amount": "190",
            "created_timestamp": 1527837382.694362,
            "display_amount": "1.90",
            "product": {
                "@type": "product",
                "currency": "PLN",
                "display_price": "29.90",
                "name": "Miesi\u0119czna Subskrypcja Learner w CoSphere.org",
                "price": "2990",
                "product_type": "SUBSCRIPTION_LEARNER_MONTHLY"
            },
            "status": "NEW",
            "status_ledger": null
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "payment_token": [
                    "This field is required."
                ]
            },
            "user_id": 484
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "400 (BROKEN)": {
        "content": {
            "@event": "BROKEN",
            "@type": "error",
            "user_id": 483
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (COULD_NOT_FIND_INVOICE)": {
        "content": {
            "@event": "COULD_NOT_FIND_INVOICE",
            "@type": "error",
            "user_id": 485
        },
        "content_type": "application/json",
        "status": 404
    }
}

/**
 * Examples for RENDER_PAYMENT_CARD_WIDGET
 */
export const RenderPaymentCardWidgetExamples = {
    "200 (PAYMENT_CARD_WIDGET_RENDERED)": {
        "content": {
            "@event": "PAYMENT_CARD_WIDGET_RENDERED",
            "@type": "payment_card_widget",
            "currency_code": "PLN",
            "customer_language": "pl",
            "merchant_pos_id": "145227",
            "recurring_payment": true,
            "shop_name": "Nazwa sklepu",
            "sig": "f8d9f8",
            "store_card": true,
            "total_amount": "0.00",
            "widget_mode": "use"
        },
        "content_type": "application/json",
        "status": 200
    }
}