/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Payment Cards Management Domain Examples
 */

/**
 * Examples for AS_DEFAULT_MARK_PAYMENTCARD
 */
export const AsDefaultMarkPaymentcardExamples = {
    
}

/**
 * Examples for BULK_READ_PAYMENTCARDS
 */
export const BulkReadPaymentcardsExamples = {
    
}

/**
 * Examples for CREATE_PAYMENTCARD
 */
export const CreatePaymentcardExamples = {
    
}

/**
 * Examples for DELETE_PAYMENTCARD
 */
export const DeletePaymentcardExamples = {
    
}

/**
 * Examples for PAY_WITH_DEFAULT_PAYMENT_CARD
 */
export const PayWithDefaultPaymentCardExamples = {
    
}

/**
 * Examples for RENDER_PAYMENT_CARD_WIDGET
 */
export const RenderPaymentCardWidgetExamples = {
    
}