/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Subscription Management Domain Examples
 */

/**
 * Examples for CHANGE_SUBSCRIPTION
 */
export const ChangeSubscriptionExamples = {
    
}