/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Tasks Management Domain Examples
 */

/**
 * Examples for BULK_READ_TASKS
 */
export const BulkReadTasksExamples = {
    "200 (TASKS_BULK_READ)": {
        "content": {
            "@event": "TASKS_BULK_READ",
            "@type": "tasks_list",
            "tasks": [
                {
                    "@type": "task",
                    "archived": false,
                    "content": {
                        "cells": [
                            {
                                "html": "hi there"
                            }
                        ]
                    },
                    "created_timestamp": 1527800206.842153,
                    "done_date": null,
                    "done_timestamp": null,
                    "id": 65,
                    "order_number": 54.0,
                    "queue_type": "HP",
                    "total_time": 310
                },
                {
                    "@type": "task",
                    "archived": false,
                    "content": {
                        "cells": [
                            {
                                "html": "hi there"
                            }
                        ]
                    },
                    "created_timestamp": 1527800206.842693,
                    "done_date": null,
                    "done_timestamp": null,
                    "id": 66,
                    "order_number": 34.0,
                    "queue_type": "HP",
                    "total_time": 421
                }
            ]
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "400 (QUERY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "QUERY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "offset": [
                    "A valid integer is required."
                ]
            },
            "user_id": 11
        },
        "content_type": "application/json",
        "status": 400
    }
}

/**
 * Examples for BULK_READ_TASK_BINS
 */
export const BulkReadTaskBinsExamples = {
    "200 (TASK_BINS_BULK_READ)": {
        "content": {
            "@event": "TASK_BINS_BULK_READ",
            "@type": "tasks_bins_list",
            "tasks_bins": [
                {
                    "@type": "tasks_bin",
                    "done_date": "2013-01-03",
                    "tasks": [
                        {
                            "@type": "task",
                            "archived": false,
                            "content": {
                                "cells": [
                                    {
                                        "html": "hi there"
                                    }
                                ]
                            },
                            "created_timestamp": 1527800206.714753,
                            "done_date": "2013-01-03",
                            "done_timestamp": 1357195500.0,
                            "id": 61,
                            "order_number": 322.0,
                            "queue_type": "DN",
                            "total_time": 453
                        }
                    ]
                }
            ]
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "400 (QUERY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "QUERY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "offset": [
                    "A valid integer is required."
                ]
            },
            "user_id": 11
        },
        "content_type": "application/json",
        "status": 400
    }
}