/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Tasks Management Domain Examples
 */

/**
 * Examples for BULK_READ_TASKS
 */
export const BulkReadTasksExamples = {
    
}

/**
 * Examples for BULK_READ_TASK_BINS
 */
export const BulkReadTaskBinsExamples = {
    
}