/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Focus Records Management Domain Examples
 */

/**
 * Examples for CREATE_FOCUSRECORD
 */
export const CreateFocusrecordExamples = {
    
}

/**
 * Examples for READ_FOCUS_RECORD_SUMMARY
 */
export const ReadFocusRecordSummaryExamples = {
    
}