/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Internal Management Domain
 */
import { Injectable } from '@angular/core';
import { filter } from 'rxjs/operators';
import { Observable } from 'rxjs';
import * as _ from 'underscore';

import { ClientService } from '../../services/client.service';
import { DataState } from '../../services/client.interface';

import * as X from './internal.models';

@Injectable()
export class InternalDomain {
    constructor(private client: ClientService) {}

    /**
     * Clear all Entries for a given User
     * -------------
     *
     * Internal view enabling one to clean up all database entries for a specific `user_id`. It must be of the utmost importance that this endpoint would not be available on the production system.
     */
    public deleteEntriesForUser(userId: any): Observable<X.DeleteEntriesForUserResponse> {
        return this.client
            .delete<X.DeleteEntriesForUserResponse>(`/reset/${userId}`, { authorizationRequired: true })
            .pipe(filter(x => !_.isEmpty(x)));
    }

}