/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Attempt Stats Management Domain Examples
 */

/**
 * Examples for BULK_READ_ATTEMPTSTATS
 */
export const BulkReadAttemptstatsExamples = {
    "200 (ATTEMPTSTATS_BULK_READ)": {
        "content": {
            "@count": 4,
            "@event": "ATTEMPTSTATS_BULK_READ",
            "@type": "attempt_stats_list",
            "attempt_stats": [
                {
                    "@type": "attempt_stat",
                    "card_id": 1940,
                    "created_timestamp": 1486555834.0,
                    "id": 108,
                    "states_path": [
                        {
                            "reached_via_event": "NEXT_LOADED",
                            "state": "SOURCE",
                            "timestamp": 943894
                        },
                        {
                            "reached_via_event": "SHOW_ANSWER",
                            "state": "TARGET",
                            "timestamp": 943994
                        },
                        {
                            "reached_via_event": "RECALL_ATTEMPT",
                            "state": "ATTEMPT",
                            "timestamp": 944994
                        },
                        {
                            "reached_via_event": "DO_NOT_GET_IT_YET",
                            "state": "NEXT",
                            "timestamp": 943994
                        }
                    ],
                    "successful": true
                },
                {
                    "@type": "attempt_stat",
                    "card_id": 1940,
                    "created_timestamp": 1486555654.0,
                    "id": 109,
                    "states_path": [
                        {
                            "reached_via_event": "NEXT_LOADED",
                            "state": "SOURCE",
                            "timestamp": 943894
                        },
                        {
                            "reached_via_event": "SHOW_ANSWER",
                            "state": "TARGET",
                            "timestamp": 943994
                        },
                        {
                            "reached_via_event": "RECALL_ATTEMPT",
                            "state": "ATTEMPT",
                            "timestamp": 944994
                        },
                        {
                            "reached_via_event": "DO_NOT_GET_IT_YET",
                            "state": "NEXT",
                            "timestamp": 943994
                        }
                    ],
                    "successful": true
                },
                {
                    "@type": "attempt_stat",
                    "card_id": 1940,
                    "created_timestamp": 1486555594.0,
                    "id": 110,
                    "states_path": [
                        {
                            "reached_via_event": "NEXT_LOADED",
                            "state": "SOURCE",
                            "timestamp": 943894
                        },
                        {
                            "reached_via_event": "SHOW_ANSWER",
                            "state": "TARGET",
                            "timestamp": 943994
                        },
                        {
                            "reached_via_event": "RECALL_ATTEMPT",
                            "state": "ATTEMPT",
                            "timestamp": 944994
                        },
                        {
                            "reached_via_event": "DO_NOT_GET_IT_YET",
                            "state": "NEXT",
                            "timestamp": 943994
                        }
                    ],
                    "successful": false
                },
                {
                    "@type": "attempt_stat",
                    "card_id": 1940,
                    "created_timestamp": 1486555534.0,
                    "id": 111,
                    "states_path": [
                        {
                            "reached_via_event": "NEXT_LOADED",
                            "state": "SOURCE",
                            "timestamp": 943894
                        },
                        {
                            "reached_via_event": "SHOW_ANSWER",
                            "state": "TARGET",
                            "timestamp": 943994
                        },
                        {
                            "reached_via_event": "RECALL_ATTEMPT",
                            "state": "ATTEMPT",
                            "timestamp": 944994
                        },
                        {
                            "reached_via_event": "DO_NOT_GET_IT_YET",
                            "state": "NEXT",
                            "timestamp": 943994
                        }
                    ],
                    "successful": true
                }
            ]
        },
        "content_type": "application/json",
        "status": 200
    }
}

/**
 * Examples for CREATE_ATTEMPTSTAT
 */
export const CreateAttemptstatExamples = {
    "201 (ATTEMPTSTAT_CREATED)": {
        "content": {
            "@event": "ATTEMPTSTAT_CREATED",
            "@type": "attempt_stat",
            "card_id": 1942,
            "created_timestamp": 1533830396.639411,
            "id": 113,
            "states_path": [
                {
                    "reached_via_event": "NEXT_LOADED",
                    "state": "SOURCE",
                    "timestamp": 943894
                },
                {
                    "reached_via_event": "SHOW_ANSWER",
                    "state": "TARGET",
                    "timestamp": 943994
                },
                {
                    "reached_via_event": "RECALL_ATTEMPT",
                    "state": "ATTEMPT",
                    "timestamp": 944994
                },
                {
                    "reached_via_event": "DO_NOT_GET_IT_YET",
                    "state": "NEXT",
                    "timestamp": 943995
                }
            ],
            "successful": false
        },
        "content_type": "application/json",
        "status": 201
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "card_id": [
                    "This field is required."
                ],
                "states_path": [
                    "This field is required."
                ]
            },
            "user_id": 78
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (COULD_NOT_FIND_CARD)": {
        "content": {
            "@event": "COULD_NOT_FIND_CARD",
            "@type": "error",
            "user_id": 78
        },
        "content_type": "application/json",
        "status": 404
    }
}

/**
 * Examples for CREATE_EXTERNAL_ATTEMPT_STAT
 */
export const CreateExternalAttemptStatExamples = {
    "201 (EXTERNAL_ATTEMPT_STAT_CREATED)": {
        "content": {
            "@event": "EXTERNAL_ATTEMPT_STAT_CREATED",
            "@type": "attempt_stat",
            "card_id": 1947,
            "created_timestamp": 1533830397.07195,
            "id": 118,
            "states_path": [
                {
                    "reached_via_event": null,
                    "state": "EXTERNAL_START",
                    "timestamp": 943894
                },
                {
                    "reached_via_event": "DID_WELL",
                    "score": 0.91,
                    "state": "EXTERNAL_STOP",
                    "timestamp": 943994
                },
                {
                    "reached_via_event": null,
                    "state": "EXTERNAL_CLOSE",
                    "timestamp": 946995
                }
            ],
            "successful": true
        },
        "content_type": "application/json",
        "status": 201
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "states_path": [
                    "This field is required."
                ]
            },
            "user_id": 78
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "400 (MISMATCHED_ORIGIN_DETECTED)": {
        "content": {
            "@event": "MISMATCHED_ORIGIN_DETECTED",
            "@type": "error",
            "user_id": 78
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "400 (MISSING_HEADER_DATA_DETECTED)": {
        "content": {
            "@event": "MISSING_HEADER_DATA_DETECTED",
            "@type": "error",
            "user_id": 78
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (COULD_NOT_FIND_CARD)": {
        "content": {
            "@event": "COULD_NOT_FIND_CARD",
            "@type": "error",
            "user_id": 78
        },
        "content_type": "application/json",
        "status": 404
    }
}