/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Fragment Words Management Domain
 */
import { Injectable } from '@angular/core';
import { filter } from 'rxjs/operators';
import { Observable } from 'rxjs';
import * as _ from 'underscore';

import { ClientService } from '../../services/client.service';
import { DataState } from '../../services/client.interface';

import * as X from './fragment_words.models';

@Injectable()
export class FragmentWordsDomain {
    constructor(private client: ClientService) {}

    /**
     * List Words
     * -------------
     *
     * List Words
     */
    public bulkReadFragmentWords(params: X.BulkReadFragmentWordsQuery): DataState<X.BulkReadFragmentWordsResponseEntity[]> {
        return this.client.getDataState<X.BulkReadFragmentWordsResponseEntity[]>('/fragments/words/', { params, responseMap: 'words', authorizationRequired: true });
    }
    
    public bulkReadFragmentWords2(params: X.BulkReadFragmentWordsQuery): Observable<X.BulkReadFragmentWordsResponseEntity[]> {
        return this.client.get<X.BulkReadFragmentWordsResponseEntity[]>('/fragments/words/', { params, responseMap: 'words', authorizationRequired: true });
    }

    /**
     * List Published Words
     * -------------
     *
     * List Published Words
     */
    public bulkReadPublishedFragmentWords(params: X.BulkReadPublishedFragmentWordsQuery): DataState<X.BulkReadPublishedFragmentWordsResponseEntity[]> {
        return this.client.getDataState<X.BulkReadPublishedFragmentWordsResponseEntity[]>('/fragments/words/published/', { params, responseMap: 'words', authorizationRequired: false });
    }
    
    public bulkReadPublishedFragmentWords2(params: X.BulkReadPublishedFragmentWordsQuery): Observable<X.BulkReadPublishedFragmentWordsResponseEntity[]> {
        return this.client.get<X.BulkReadPublishedFragmentWordsResponseEntity[]>('/fragments/words/published/', { params, responseMap: 'words', authorizationRequired: false });
    }

}