/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Fragment Words Management Domain Examples
 */

/**
 * Examples for BULK_READ_FRAGMENT_WORDS
 */
export const BulkReadFragmentWordsExamples = {
    "200 (FRAGMENT_WORDS_BULK_READ)": {
        "content": {
            "@event": "FRAGMENT_WORDS_BULK_READ",
            "@type": "words_list",
            "words": [
                {
                    "@type": "word",
                    "count": 1,
                    "id": 130,
                    "text": "records"
                }
            ]
        },
        "content_type": "application/json",
        "status": 200
    }
}

/**
 * Examples for BULK_READ_PUBLISHED_FRAGMENT_WORDS
 */
export const BulkReadPublishedFragmentWordsExamples = {
    "200 (PUBLISHED_FRAGMENT_WORDS_BULK_READ)": {
        "content": {
            "@event": "PUBLISHED_FRAGMENT_WORDS_BULK_READ",
            "@type": "words_list",
            "words": [
                {
                    "@type": "word",
                    "count": 1,
                    "id": 141,
                    "text": "records"
                }
            ]
        },
        "content_type": "application/json",
        "status": 200
    }
}