/**
  * THIS FILE WILL BE AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

import { NgModule } from '@angular/core';

/** Services */
import { APIService } from './services/api.service';

@NgModule({
    providers: [
        // Facade
        APIService,
    ]
})
export class ClientModule {}
