/**
  * THIS FILE WILL BE AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

import { NgModule, ModuleWithProviders } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';

/** Services */
import { ClientService } from './services/client.service';
import { APIService } from './services/api.service';
import { Config } from './services/config.interface';

@NgModule({
    imports: [HttpClientModule],
    providers: [
        ClientService,

        // Facade
        APIService,
    ]
})
export class ClientModule {
    static forRoot(config: Config): ModuleWithProviders {
        return {
            ngModule: ClientModule,
            providers: [
                { provide: 'config', useValue: config }
            ]
        };
    }
}
