/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Categories Management Domain Examples
 */

/**
 * Examples for BULK_READ_CATEGORIES
 */
export const BulkReadCategoriesExamples = {
    
}