/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Categories Management Domain Examples
 */

/**
 * Examples for BULK_READ_CATEGORIES
 */
export const BulkReadCategoriesExamples = {
    "200 (CATEGORIES_BULK_READ)": {
        "content": {
            "@event": "CATEGORIES_BULK_READ",
            "@type": "categories_list",
            "categories": [
                {
                    "@type": "category",
                    "count": 3,
                    "id": 7,
                    "text": "problematic"
                },
                {
                    "@type": "category",
                    "count": 2,
                    "id": 8,
                    "text": "not recalled"
                },
                {
                    "@type": "category",
                    "count": 4,
                    "id": 9,
                    "text": "old"
                }
            ]
        },
        "content_type": "application/json",
        "status": 200
    }
}