/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Auth Tokens Management Domain Examples
 */

/**
 * Examples for AUTHORIZE_AUTH_TOKEN
 */
export const AuthorizeAuthTokenExamples = {
    
}

/**
 * Examples for CREATE_AUTH_TOKEN
 */
export const CreateAuthTokenExamples = {
    
}

/**
 * Examples for CREATE_FACEBOOK_BASED_AUTH_TOKEN
 */
export const CreateFacebookBasedAuthTokenExamples = {
    
}

/**
 * Examples for CREATE_FACEBOOK_BASED_MOBILE_AUTH_TOKEN
 */
export const CreateFacebookBasedMobileAuthTokenExamples = {
    
}

/**
 * Examples for CREATE_GOOGLE_BASED_AUTH_TOKEN
 */
export const CreateGoogleBasedAuthTokenExamples = {
    
}

/**
 * Examples for CREATE_GOOGLE_BASED_MOBILE_AUTH_TOKEN
 */
export const CreateGoogleBasedMobileAuthTokenExamples = {
    
}

/**
 * Examples for UPDATE_AUTH_TOKEN
 */
export const UpdateAuthTokenExamples = {
    
}