/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Geometries Management Domain Models
 */

/**
 * https://bitbucket.org/goodai/cosphere-entity-service/src/5f215fabba7fa3925151c098fad0051162452821/cosphere_entity_service/grid/views.py/#lines-150
 */

export interface BulkReadGeometriesQuery {
    height?: number;
    width?: number;
    x?: number;
    y?: number;
}

/**
 * https://bitbucket.org/goodai/cosphere-entity-service/src/5f215fabba7fa3925151c098fad0051162452821/cosphere_entity_service/grid/serializers.py/#lines-55
 */

export interface BulkReadGeometriesResponseEntity {
    card_id?: any;
    id?: number;
    is_random?: boolean;
    recall_score?: number;
    x?: number;
    y?: number;
}

export interface BulkReadGeometriesResponse {
    geometries: BulkReadGeometriesResponseEntity[];
}

/**
 * https://bitbucket.org/goodai/cosphere-entity-service/src/5f215fabba7fa3925151c098fad0051162452821/cosphere_entity_service/grid/views.py/#lines-190
 */

export interface BulkUpdateGeometriesBody {
    data: Object[];
}

/**
 * https://bitbucket.org/goodai/cosphere-entity-service/src/5f215fabba7fa3925151c098fad0051162452821/cosphere_entity_service/grid/serializers.py/#lines-55
 */

export interface BulkUpdateGeometriesResponse {
    geometries: {
        card_id?: any;
        id?: number;
        is_random?: boolean;
        recall_score?: number;
        x?: number;
        y?: number;
    }[];
}

/**
 * https://bitbucket.org/goodai/cosphere-entity-service/src/5f215fabba7fa3925151c098fad0051162452821/cosphere_entity_service/grid/serializers.py/#lines-39
 */

export interface ReadGeometryByCardResponse {
    card_id?: any;
    id?: number;
    is_random?: boolean;
    recall_score?: number;
    x?: number;
    y?: number;
}

/**
 * https://bitbucket.org/goodai/cosphere-entity-service/src/5f215fabba7fa3925151c098fad0051162452821/cosphere_entity_service/grid/views.py/#lines-150
 */

export interface ReadGraphQuery {
    card_ids: number[];
}

/**
 * https://bitbucket.org/goodai/cosphere-entity-service/src/5f215fabba7fa3925151c098fad0051162452821/cosphere_entity_service/grid/serializers.py/#lines-62
 */

export interface ReadGraphResponse {
    links: {
        source: number;
        target: number;
        value: number;
    }[];
    nodes: {
        id: number;
        x: number;
        y: number;
    }[];
}