/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Payments Management Domain Models
 */

/**
 * https://bitbucket.org/goodai/cosphere-auth-service/src/69bb55b04713846fc3aa1a1c300a8a9ed207b2d3/cosphere_auth_service/payment/views/payment.py/#lines-15
 */

export interface UpdatePaymentStatusBody {
    order: {
        extOrderId: string;
        merchantPosId: string;
        status: string;
    };
}

/**
 * https://bitbucket.org/goodai/cosphere-auth-service/src/69bb55b04713846fc3aa1a1c300a8a9ed207b2d3/.venv/src/lily/lily/base/serializers.py/#lines-158
 */

export interface UpdatePaymentStatusResponse {}