/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Attempts Management Domain Models
 */

/**
 * https://bitbucket.org/goodai/cosphere-entity-service/src/5f215fabba7fa3925151c098fad0051162452821/cosphere_entity_service/recall/serializers.py/#lines-29
 */

export interface BulkReadAttemptsByCardsResponseEntity {
    card_id: number;
    cells?: Object;
    id?: number;
    style?: Object;
}

export interface BulkReadAttemptsByCardsResponse {
    attempts: BulkReadAttemptsByCardsResponseEntity[];
}

/**
 * https://bitbucket.org/goodai/cosphere-entity-service/src/5f215fabba7fa3925151c098fad0051162452821/cosphere_entity_service/recall/views.py/#lines-88
 */

export interface CreateAttemptBody {
    card_id: number;
    cells: Object;
    style?: Object;
}

/**
 * https://bitbucket.org/goodai/cosphere-entity-service/src/5f215fabba7fa3925151c098fad0051162452821/cosphere_entity_service/recall/serializers.py/#lines-9
 */

export interface CreateAttemptResponse {
    card_id: number;
    cells?: Object;
    id?: number;
    style?: Object;
}

/**
 * https://bitbucket.org/goodai/cosphere-entity-service/src/5f215fabba7fa3925151c098fad0051162452821/cosphere_entity_service/recall/views.py/#lines-60
 */

export interface UpdateAttemptBody {
    cells: Object;
    style?: Object;
}

/**
 * https://bitbucket.org/goodai/cosphere-entity-service/src/5f215fabba7fa3925151c098fad0051162452821/cosphere_entity_service/recall/serializers.py/#lines-9
 */

export interface UpdateAttemptResponse {
    card_id: number;
    cells?: Object;
    id?: number;
    style?: Object;
}