/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Attempts Management Domain Examples
 */

/**
 * Examples for BULK_READ_ATTEMPTS_BY_CARDS
 */
export const BulkReadAttemptsByCardsExamples = {
    "200 (ATTEMPTS_BY_CARDS_BULK_READ)": {
        "content": {
            "@event": "ATTEMPTS_BY_CARDS_BULK_READ",
            "@type": "attempts_list",
            "attempts": [
                {
                    "@type": "attempt",
                    "card_id": 1936,
                    "cells": [
                        {
                            "html": "Dolorem nisi at reprehenderit laudantium pariatur beatae.",
                            "id": "56678mefd",
                            "name": "text cell",
                            "style": {
                                "backgroundColor": "transparent",
                                "color": "#fff",
                                "fontSize": "150%",
                                "height": "auto",
                                "left": "30px",
                                "textAlign": "left",
                                "top": "0px",
                                "width": "100px",
                                "zIndex": 1
                            },
                            "subtype": "PARAGRAPH",
                            "type": "TEXT"
                        }
                    ],
                    "id": 25,
                    "style": {
                        "backgroundColor": "yellow"
                    }
                },
                {
                    "@type": "attempt",
                    "card_id": 1936,
                    "cells": [
                        {
                            "html": "Magni totam dolore neque incidunt nisi.",
                            "id": "56678mefd",
                            "name": "text cell",
                            "style": {
                                "backgroundColor": "transparent",
                                "color": "#fff",
                                "fontSize": "150%",
                                "height": "auto",
                                "left": "30px",
                                "textAlign": "left",
                                "top": "0px",
                                "width": "100px",
                                "zIndex": 1
                            },
                            "subtype": "PARAGRAPH",
                            "type": "TEXT"
                        }
                    ],
                    "id": 24,
                    "style": {
                        "backgroundColor": "yellow"
                    }
                },
                {
                    "@type": "attempt",
                    "card_id": 1936,
                    "cells": [
                        {
                            "html": "Voluptate fugiat perferendis itaque sed.",
                            "id": "56678mefd",
                            "name": "text cell",
                            "style": {
                                "backgroundColor": "transparent",
                                "color": "#fff",
                                "fontSize": "150%",
                                "height": "auto",
                                "left": "30px",
                                "textAlign": "left",
                                "top": "0px",
                                "width": "100px",
                                "zIndex": 1
                            },
                            "subtype": "PARAGRAPH",
                            "type": "TEXT"
                        }
                    ],
                    "id": 23,
                    "style": {
                        "backgroundColor": "yellow"
                    }
                }
            ]
        },
        "content_type": "application/json",
        "status": 200
    }
}

/**
 * Examples for CREATE_ATTEMPT
 */
export const CreateAttemptExamples = {
    "201 (ATTEMPT_CREATED)": {
        "content": {
            "@event": "ATTEMPT_CREATED",
            "@type": "attempt",
            "card_id": 1925,
            "cells": [
                {
                    "html": "some attempt cells",
                    "id": "56678mefd",
                    "name": "text cell",
                    "style": {
                        "backgroundColor": "transparent",
                        "color": "#fff",
                        "fontSize": "150%",
                        "height": "auto",
                        "left": "30px",
                        "textAlign": "left",
                        "top": "0px",
                        "width": "100px",
                        "zIndex": 1
                    },
                    "subtype": "PARAGRAPH",
                    "type": "TEXT"
                }
            ],
            "id": 15,
            "style": {
                "backgroundColor": "gray"
            }
        },
        "content_type": "application/json",
        "status": 201
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "cells": [
                    "This field is required."
                ]
            },
            "user_id": 78
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (COULD_NOT_FIND_CARD)": {
        "content": {
            "@event": "COULD_NOT_FIND_CARD",
            "@type": "error",
            "user_id": 78
        },
        "content_type": "application/json",
        "status": 404
    }
}

/**
 * Examples for UPDATE_ATTEMPT
 */
export const UpdateAttemptExamples = {
    "200 (ATTEMPT_UPDATED)": {
        "content": {
            "@event": "ATTEMPT_UPDATED",
            "@type": "attempt",
            "card_id": 1930,
            "cells": [
                {
                    "html": "2!",
                    "id": "56678mefd",
                    "name": "text cell",
                    "style": {
                        "backgroundColor": "transparent",
                        "color": "#fff",
                        "fontSize": "150%",
                        "height": "auto",
                        "left": "30px",
                        "textAlign": "left",
                        "top": "0px",
                        "width": "100px",
                        "zIndex": 1
                    },
                    "subtype": "PARAGRAPH",
                    "type": "TEXT"
                }
            ],
            "id": 17,
            "style": {
                "backgroundColor": "yellow"
            }
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "cells": [
                    "This field is required."
                ]
            },
            "user_id": 78
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (COULD_NOT_FIND_ATTEMPT)": {
        "content": {
            "@event": "COULD_NOT_FIND_ATTEMPT",
            "@type": "error",
            "user_id": 78
        },
        "content_type": "application/json",
        "status": 404
    }
}