/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Gossip Commands Management Domain Examples
 */

/**
 * Examples for BULK_READ_SPEECH_LANGUAGES
 */
export const BulkReadSpeechLanguagesExamples = {
    "200 (SPEECH_LANGUAGES_BULK_READ)": {
        "content": {
            "@event": "SPEECH_LANGUAGES_BULK_READ",
            "@type": "languages_list",
            "languages": [
                {
                    "@type": "language",
                    "abbr": "de",
                    "name": "German"
                },
                {
                    "@type": "language",
                    "abbr": "en",
                    "name": "English"
                }
            ]
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "500 (GENERIC_ERROR_OCCURRED)": {
        "content": {
            "@event": "GENERIC_ERROR_OCCURRED",
            "@type": "error",
            "errors": [
                "'language_name'"
            ],
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 500
    }
}

/**
 * Examples for BULK_READ_TEXT_LANGUAGES
 */
export const BulkReadTextLanguagesExamples = {
    "200 (TEXT_LANGUAGES_BULK_READ)": {
        "content": {
            "@event": "TEXT_LANGUAGES_BULK_READ",
            "@type": "languages_list",
            "languages": [
                {
                    "@type": "language",
                    "abbr": "de",
                    "name": "German"
                },
                {
                    "@type": "language",
                    "abbr": "en",
                    "name": "English"
                },
                {
                    "@type": "language",
                    "abbr": "ru",
                    "name": "Russian"
                }
            ]
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "500 (GENERIC_ERROR_OCCURRED)": {
        "content": {
            "@event": "GENERIC_ERROR_OCCURRED",
            "@type": "error",
            "errors": [
                "'language_abbr'"
            ],
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 500
    }
}

/**
 * Examples for DETECT_SPEECH_LANGUAGES
 */
export const DetectSpeechLanguagesExamples = {
    "200 (SPEECH_LANGUAGES_DETECTED)": {
        "content": {
            "@event": "SPEECH_LANGUAGES_DETECTED",
            "@type": "languages_list",
            "languages": [
                {
                    "@type": "language",
                    "abbr": "pl",
                    "name": "Polish"
                }
            ]
        },
        "content_type": "application/json",
        "status": 200
    }
}

/**
 * Examples for DETECT_TEXT_LANGUAGES
 */
export const DetectTextLanguagesExamples = {
    
}