/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Accounts Management Domain
 */
import { Injectable } from '@angular/core';
import { filter } from 'rxjs/operators';
import { Observable } from 'rxjs';
import * as _ from 'underscore';

import { ClientService } from '../../services/client.service';
import { DataState } from '../../services/client.interface';

import * as X from './accounts.models';

@Injectable()
export class AccountsDomain {
    constructor(private client: ClientService) {}

    /**
     * Activate Account
     * -------------
     *
     * Activate Account by decoding the `code` which contains the confirmation off the intent and was signed by the user itself.
     */
    public activateAccount(body: X.ActivateAccountBody): Observable<X.ActivateAccountResponse> {
        return this.client
            .post<X.ActivateAccountResponse>('/auth/activate/', body, { authorizationRequired: false })
            .pipe(filter(x => !_.isEmpty(x)));
    }

    /**
     * Bulk Read Mentors' Account
     * -------------
     *
     * Enable one to Read all available Mentor accounts
     */
    public bulkReadAccounts(params: X.BulkReadAccountsQuery): DataState<X.BulkReadAccountsResponseEntity[]> {
        return this.client.getDataState<X.BulkReadAccountsResponseEntity[]>('/auth/accounts/', { params, responseMap: 'data', authorizationRequired: true });
    }

    /**
     * Change Password
     * -------------
     *
     * Enables one to change one's password for an authenticated user.
     */
    public changePassword(body: X.ChangePasswordBody): Observable<X.ChangePasswordResponse> {
        return this.client
            .post<X.ChangePasswordResponse>('/auth/change_password/', body, { authorizationRequired: true })
            .pipe(filter(x => !_.isEmpty(x)));
    }

    /**
     * Create Account
     * -------------
     *
     * Creates User and Account if provided data are valid.
     */
    public createAccount(body: X.CreateAccountBody): Observable<X.CreateAccountResponse> {
        return this.client
            .post<X.CreateAccountResponse>('/auth/accounts/', body, { authorizationRequired: false })
            .pipe(filter(x => !_.isEmpty(x)));
    }

    /**
     * Read My Account
     * -------------
     *
     * Read my Account data.
     */
    public readAccount(): DataState<X.ReadAccountResponse> {
        return this.client.getDataState<X.ReadAccountResponse>('/auth/accounts/me/', { authorizationRequired: true });
    }

    /**
     * Reset Password
     * -------------
     *
     * Enables one to reset her password in case the old one cannot be recalled.
     */
    public resetPassword(body: X.ResetPasswordBody): Observable<X.ResetPasswordResponse> {
        return this.client
            .post<X.ResetPasswordResponse>('/auth/reset_password/', body, { authorizationRequired: false })
            .pipe(filter(x => !_.isEmpty(x)));
    }

    /**
     * Send Account Activation Email
     * -------------
     *
     * Send an Email containing the confirmation link which when clicked kicks of the Account Activation. Even though the activation email is send automatically during the Sign Up phase one should have a way to send it again in case it was not delivered.
     */
    public sendAccountActivationEmail(body: X.SendAccountActivationEmailBody): Observable<X.SendAccountActivationEmailResponse> {
        return this.client
            .post<X.SendAccountActivationEmailResponse>('/auth/send_activation_email/', body, { authorizationRequired: false })
            .pipe(filter(x => !_.isEmpty(x)));
    }

    /**
     * Send Reset Password Email
     * -------------
     *
     * Send an Email containing the confirmation link which when clicked kicks of the real Reset Password operation.
     */
    public sendResetPasswordEmail(body: X.SendResetPasswordEmailBody): Observable<X.SendResetPasswordEmailResponse> {
        return this.client
            .post<X.SendResetPasswordEmailResponse>('/auth/send_reset_password_email/', body, { authorizationRequired: false })
            .pipe(filter(x => !_.isEmpty(x)));
    }

    /**
     * Update My Account
     * -------------
     *
     * Update my Account data.
     */
    public updateAccount(body: X.UpdateAccountBody): Observable<X.UpdateAccountResponse> {
        return this.client
            .put<X.UpdateAccountResponse>('/auth/accounts/me/', body, { authorizationRequired: true })
            .pipe(filter(x => !_.isEmpty(x)));
    }

}