/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Accounts Management Domain Examples
 */

/**
 * Examples for ACTIVATE_ACCOUNT
 */
export const ActivateAccountExamples = {
    
}

/**
 * Examples for BULK_READ_ACCOUNTS
 */
export const BulkReadAccountsExamples = {
    
}

/**
 * Examples for CHANGE_PASSWORD
 */
export const ChangePasswordExamples = {
    
}

/**
 * Examples for CREATE_ACCOUNT
 */
export const CreateAccountExamples = {
    
}

/**
 * Examples for READ_ACCOUNT
 */
export const ReadAccountExamples = {
    
}

/**
 * Examples for RESET_PASSWORD
 */
export const ResetPasswordExamples = {
    
}

/**
 * Examples for SEND_ACCOUNT_ACTIVATION_EMAIL
 */
export const SendAccountActivationEmailExamples = {
    
}

/**
 * Examples for SEND_RESET_PASSWORD_EMAIL
 */
export const SendResetPasswordEmailExamples = {
    
}

/**
 * Examples for UPDATE_ACCOUNT
 */
export const UpdateAccountExamples = {
    
}