/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Fragments Management Domain Examples
 */

/**
 * Examples for BULK_READ_FRAGMENTS
 */
export const BulkReadFragmentsExamples = {
    
}

/**
 * Examples for BULK_READ_PUBLISHED_FRAGMENTS
 */
export const BulkReadPublishedFragmentsExamples = {
    
}

/**
 * Examples for CREATE_FRAGMENT
 */
export const CreateFragmentExamples = {
    
}

/**
 * Examples for DELETE_FRAGMENT
 */
export const DeleteFragmentExamples = {
    
}

/**
 * Examples for MERGE_FRAGMENT
 */
export const MergeFragmentExamples = {
    
}

/**
 * Examples for PUBLISH_FRAGMENT
 */
export const PublishFragmentExamples = {
    
}

/**
 * Examples for READ_FRAGMENT
 */
export const ReadFragmentExamples = {
    
}

/**
 * Examples for READ_FRAGMENT_DIFF
 */
export const ReadFragmentDiffExamples = {
    
}

/**
 * Examples for READ_FRAGMENT_SAMPLE
 */
export const ReadFragmentSampleExamples = {
    
}

/**
 * Examples for UPDATE_FRAGMENT
 */
export const UpdateFragmentExamples = {
    
}