/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Links Management Domain Examples
 */

/**
 * Examples for DELETE_LINK
 */
export const DeleteLinkExamples = {
    
}

/**
 * Examples for READ_OR_CREATE_LINK
 */
export const ReadOrCreateLinkExamples = {
    
}