/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Donations Management Domain Examples
 */

/**
 * Examples for CHECK_IF_CAN_ATTEMPT_DONATION
 */
export const CheckIfCanAttemptDonationExamples = {
    
}

/**
 * Examples for CREATE_ANONYMOUS_DONATION
 */
export const CreateAnonymousDonationExamples = {
    
}

/**
 * Examples for CREATE_DONATION
 */
export const CreateDonationExamples = {
    
}

/**
 * Examples for CREATE_DONATIONATTEMPT
 */
export const CreateDonationattemptExamples = {
    
}