/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Quizzer Entities Management Domain Examples
 */

/**
 * Examples for BULK_READ_QUIZATTEMPTS
 */
export const BulkReadQuizattemptsExamples = {
    "200 (QUIZATTEMPTS_BULK_READ)": {
        "content": {
            "@event": "QUIZATTEMPTS_BULK_READ",
            "@type": "quiz_attempts_list",
            "quiz_attempts": [
                {
                    "@type": "quiz_attempt",
                    "created_timestamp": 1533995721.917835,
                    "id": 7,
                    "is_correct": false,
                    "marked_answer_id": 1,
                    "quiz_id": 21,
                    "start_timestamp": 1533995721.917694,
                    "user_id": 190
                },
                {
                    "@type": "quiz_attempt",
                    "created_timestamp": 1533995721.918412,
                    "id": 8,
                    "is_correct": false,
                    "marked_answer_id": 5,
                    "quiz_id": 21,
                    "start_timestamp": 1533995721.918289,
                    "user_id": 191
                },
                {
                    "@type": "quiz_attempt",
                    "created_timestamp": 1533995721.918874,
                    "id": 9,
                    "is_correct": false,
                    "marked_answer_id": 0,
                    "quiz_id": 21,
                    "start_timestamp": 1533995721.918755,
                    "user_id": 190
                }
            ]
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "400 (RESPONSE_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "RESPONSE_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "quiz_attempts": [
                    "This field is required."
                ]
            },
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "403 (ACCESS_DENIED)": {
        "content": {
            "@event": "ACCESS_DENIED",
            "@type": "error",
            "user_id": "anonymous"
        },
        "content_type": "application/json",
        "status": 403
    }
}

/**
 * Examples for BULK_READ_QUIZZES
 */
export const BulkReadQuizzesExamples = {
    "200 (QUIZZES_BULK_READ)": {
        "content": {
            "@event": "QUIZZES_BULK_READ",
            "@type": "quizzes_list",
            "quizzes": [
                {
                    "@type": "quiz",
                    "answers": [
                        {
                            "answer": "Tell particularly bank next machine gas common.",
                            "id": 0,
                            "is_correct": true
                        }
                    ],
                    "id": 10,
                    "question": "Probably anyone up.",
                    "terms": [
                        "work"
                    ],
                    "title": "Simple consider modern send something to.",
                    "user_id": 190
                },
                {
                    "@type": "quiz",
                    "answers": [
                        {
                            "answer": "Check surface current economic land yard term.",
                            "id": 0,
                            "is_correct": true
                        }
                    ],
                    "id": 11,
                    "question": "Draw room down floor.",
                    "terms": [
                        "practice"
                    ],
                    "title": "Throw possible start.",
                    "user_id": 190
                }
            ]
        },
        "content_type": "application/json",
        "status": 200
    }
}

/**
 * Examples for CREATE_QUIZ
 */
export const CreateQuizExamples = {
    "201 (QUIZ_CREATED)": {
        "content": {
            "@event": "QUIZ_CREATED",
            "@type": "quiz",
            "answers": [
                {
                    "answer": "hi",
                    "id": 18,
                    "is_correct": true
                }
            ],
            "id": 13,
            "question": "how are you?",
            "terms": [
                "#hi"
            ],
            "title": "the mood",
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 201
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "terms": [
                    "JSON did not validate. PATH: '0' REASON: 123 is not of type 'string'"
                ],
                "title": [
                    "This field is required."
                ]
            },
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "500 (DATABASE_ERROR_OCCURRED)": {
        "content": {
            "@event": "DATABASE_ERROR_OCCURRED",
            "@type": "error",
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 500
    },
    
    "500 (GENERIC_ERROR_OCCURRED)": {
        "content": {
            "@event": "GENERIC_ERROR_OCCURRED",
            "@type": "error",
            "errors": [
                "Each Serializer must have `type` specified which informs the client about the semantic type a result of the Serializer represents"
            ],
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 500
    }
}

/**
 * Examples for CREATE_QUIZATTEMPT
 */
export const CreateQuizattemptExamples = {
    "201 (QUIZATTEMPT_CREATED)": {
        "content": {
            "@event": "QUIZATTEMPT_CREATED",
            "@type": "quiz_attempt",
            "created_timestamp": 1533995721.948352,
            "id": 12,
            "is_correct": true,
            "marked_answer_id": 1,
            "quiz_id": 24,
            "start_timestamp": 1536687101.0,
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 201
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "marked_answer_id": [
                    "A valid integer is required."
                ]
            },
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (COULD_NOT_FIND_MARKED_ANSWER_ID)": {
        "content": {
            "@event": "COULD_NOT_FIND_MARKED_ANSWER_ID",
            "@type": "error",
            "available_answer_ids": [
                1
            ],
            "marked_answer_id": 2,
            "user_id": null
        },
        "content_type": "application/json",
        "status": 404
    },
    
    "404 (COULD_NOT_FIND_QUIZ)": {
        "content": {
            "@event": "COULD_NOT_FIND_QUIZ",
            "@type": "error",
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 404
    },
    
    "500 (DATABASE_ERROR_OCCURRED)": {
        "content": {
            "@event": "DATABASE_ERROR_OCCURRED",
            "@type": "error",
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 500
    },
    
    "500 (GENERIC_ERROR_OCCURRED)": {
        "content": {
            "@event": "GENERIC_ERROR_OCCURRED",
            "@type": "error",
            "errors": [
                "'Quiz' object has no attribute 'answer'"
            ],
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 500
    }
}

/**
 * Examples for DELETE_QUIZ
 */
export const DeleteQuizExamples = {
    "200 (QUIZ_DELETED)": {
        "content": {
            "@event": "QUIZ_DELETED",
            "@type": "empty"
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "400 (QUIZ_WITH_ATTTEMPTS_DETECTED)": {
        "content": {
            "@event": "QUIZ_WITH_ATTTEMPTS_DETECTED",
            "@type": "error",
            "attempts_count": 1,
            "quiz_id": "15",
            "user_id": null
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (COULD_NOT_FIND_QUIZ)": {
        "content": {
            "@event": "COULD_NOT_FIND_QUIZ",
            "@type": "error",
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 404
    }
}

/**
 * Examples for READ_QUIZ
 */
export const ReadQuizExamples = {
    "200 (QUIZ_READ)": {
        "content": {
            "@event": "QUIZ_READ",
            "@type": "quiz",
            "answers": [
                {
                    "answer": "Order six son treatment daughter picture ever.",
                    "id": 0,
                    "is_correct": true
                }
            ],
            "id": 17,
            "question": "Industry once east guy safe far do here.",
            "terms": [
                "minute"
            ],
            "title": "Charge available how party sing century where.",
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "403 (ACCESS_DENIED)": {
        "content": {
            "@event": "ACCESS_DENIED",
            "@type": "error",
            "user_id": "anonymous"
        },
        "content_type": "application/json",
        "status": 403
    },
    
    "404 (COULD_NOT_FIND_QUIZ)": {
        "content": {
            "@event": "COULD_NOT_FIND_QUIZ",
            "@type": "error",
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 404
    }
}

/**
 * Examples for UPDATE_QUIZ
 */
export const UpdateQuizExamples = {
    "200 (QUIZ_UPDATED)": {
        "content": {
            "@event": "QUIZ_UPDATED",
            "@type": "quiz",
            "answers": [
                {
                    "answer": "hi",
                    "id": 18,
                    "is_correct": true
                }
            ],
            "id": 18,
            "question": "how are you?",
            "terms": [
                "#hi"
            ],
            "title": "new one",
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "question": [
                    "This field is required."
                ]
            },
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (COULD_NOT_FIND_QUIZ)": {
        "content": {
            "@event": "COULD_NOT_FIND_QUIZ",
            "@type": "error",
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 404
    },
    
    "500 (GENERIC_ERROR_OCCURRED)": {
        "content": {
            "@event": "GENERIC_ERROR_OCCURRED",
            "@type": "error",
            "errors": [
                "too many values to unpack (expected 2)"
            ],
            "user_id": 190
        },
        "content_type": "application/json",
        "status": 500
    }
}