/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * External Apps Management Domain Examples
 */

/**
 * Examples for AUTHORIZE_EXTERNAL_APP_AUTH_TOKEN
 */
export const AuthorizeExternalAppAuthTokenExamples = {
    
}

/**
 * Examples for CREATE_EXTERNAL_APP_AUTH_TOKEN
 */
export const CreateExternalAppAuthTokenExamples = {
    
}

/**
 * Examples for READ_EXTERNALAPPCONF
 */
export const ReadExternalappconfExamples = {
    
}