/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * External Apps Management Domain Examples
 */

/**
 * Examples for AUTHORIZE_EXTERNAL_APP_AUTH_TOKEN
 */
export const AuthorizeExternalAppAuthTokenExamples = {
    "200 (EXTERNAL_APP_AUTH_TOKEN_AUTHORIZED)": {
        "content": {
            "@event": "EXTERNAL_APP_AUTH_TOKEN_AUTHORIZED",
            "@type": "empty"
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "401 (AUTH_TOKEN_WAS_BROKEN)": {
        "content": {
            "@event": "AUTH_TOKEN_WAS_BROKEN",
            "@type": "error",
            "user_id": "anonymous"
        },
        "content_type": "application/json",
        "status": 401
    }
}

/**
 * Examples for CREATE_EXTERNAL_APP_AUTH_TOKEN
 */
export const CreateExternalAppAuthTokenExamples = {
    "201 (EXTERNAL_APP_AUTH_TOKEN_CREATED)": {
        "content": {
            "@event": "EXTERNAL_APP_AUTH_TOKEN_CREATED",
            "@type": "external_app_auth_token",
            "token": "007.token.008"
        },
        "content_type": "application/json",
        "status": 201
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "card_id": [
                    "This field is required."
                ]
            },
            "user_id": 315
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (COULD_NOT_FIND_EXTERNALAPPCONF)": {
        "content": {
            "@event": "COULD_NOT_FIND_EXTERNALAPPCONF",
            "@type": "error",
            "user_id": 317
        },
        "content_type": "application/json",
        "status": 404
    },
    
    "404 (COULD_NOT_FIND_USER)": {
        "content": {
            "@event": "COULD_NOT_FIND_USER",
            "@type": "error",
            "user_id": 5769758
        },
        "content_type": "application/json",
        "status": 404
    },
    
    "500 (FOUND_MULTIPLE_INSTANCES_OF_EXTERNALAPPCONF)": {
        "content": {
            "@event": "FOUND_MULTIPLE_INSTANCES_OF_EXTERNALAPPCONF",
            "@type": "error",
            "user_id": 316
        },
        "content_type": "application/json",
        "status": 500
    }
}

/**
 * Examples for READ_EXTERNALAPPCONF
 */
export const ReadExternalappconfExamples = {
    "200 (EXTERNALAPPCONF_READ)": {
        "content": {
            "@event": "EXTERNALAPPCONF_READ",
            "@type": "external_app_conf",
            "id": 12,
            "logo_uri": "https://crazy.com/abc.png",
            "source_bg_color": "#000001",
            "source_fg_color": "#590656",
            "target_bg_color": "#569034",
            "target_fg_color": "#100000",
            "uri_pattern": "https://awesome.io/games/[0-9]+"
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "400 (QUERY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "QUERY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "uri": [
                    "This field is required."
                ]
            },
            "user_id": 310
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (COULD_NOT_FIND_EXTERNALAPPCONF)": {
        "content": {
            "@event": "COULD_NOT_FIND_EXTERNALAPPCONF",
            "@type": "error",
            "user_id": 312
        },
        "content_type": "application/json",
        "status": 404
    },
    
    "500 (FOUND_MULTIPLE_INSTANCES_OF_EXTERNALAPPCONF)": {
        "content": {
            "@event": "FOUND_MULTIPLE_INSTANCES_OF_EXTERNALAPPCONF",
            "@type": "error",
            "user_id": 311
        },
        "content_type": "application/json",
        "status": 500
    }
}