/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Invoice Management Domain Examples
 */

/**
 * Examples for BULK_READ_INVOICES
 */
export const BulkReadInvoicesExamples = {
    
}

/**
 * Examples for CALCULATE_DEBT
 */
export const CalculateDebtExamples = {
    
}