/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Invoice Management Domain Examples
 */

/**
 * Examples for BULK_READ_INVOICES
 */
export const BulkReadInvoicesExamples = {
    "200 (INVOICES_BULK_READ)": {
        "content": {
            "@event": "INVOICES_BULK_READ",
            "@type": "invoices_list",
            "invoices": [
                {
                    "@type": "invoice",
                    "amount": "121",
                    "created_timestamp": 1510576260.0,
                    "currency": "EUR",
                    "display_amount": "1.21",
                    "id": 34,
                    "is_extension": false,
                    "paid_till_timestamp": 1511440260.0,
                    "product": {
                        "@type": "product",
                        "currency": "PLN",
                        "display_price": "29.90",
                        "name": "Miesi\u0119czna Subskrypcja Learner w CoSphere.org",
                        "price": "2990",
                        "product_type": "SUBSCRIPTION_LEARNER_MONTHLY"
                    },
                    "surplus_amount": "117",
                    "surplus_currency": "USD",
                    "valid_till_timestamp": 1513211460.0
                }
            ]
        },
        "content_type": "application/json",
        "status": 200
    }
}

/**
 * Examples for CALCULATE_DEBT
 */
export const CalculateDebtExamples = {
    "200 (DEBT_CALCULATED)": {
        "content": {
            "@commands": {
                "PAY_WITH_DEFAULT_PAYMENT_CARD": {}
            },
            "@event": "DEBT_CALCULATED",
            "@type": "debt",
            "currency": "EUR",
            "display_owes": "2.11",
            "owes": 211
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "400 (RESPONSE_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "RESPONSE_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "at__commands": {
                    "method": [
                        "This field is required."
                    ],
                    "name": [
                        "This field is required."
                    ],
                    "uri": [
                        "This field is required."
                    ]
                }
            },
            "user_id": 1
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (NO_DEBT_CALCULATED)": {
        "content": {
            "@event": "NO_DEBT_CALCULATED",
            "@type": "error",
            "user_id": 450
        },
        "content_type": "application/json",
        "status": 404
    },
    
    "500 (GENERIC_ERROR_OCCURRED)": {
        "content": {
            "@event": "GENERIC_ERROR_OCCURRED",
            "@type": "error",
            "errors": [
                "'body'"
            ],
            "user_id": 3
        },
        "content_type": "application/json",
        "status": 500
    }
}