/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Processes Management Domain Models
 */

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/cosphere_media_service/mediafile/views.py/#lines-111
 */

export interface CreateDeletionProcessBody {
    content_uris: string[];
}

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/cosphere_media_service/mediafile/views.py/#lines-102
 */

export interface CreateDeletionProcessResponse {
    process_id: string;
}

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/cosphere_media_service/mediafile/views.py/#lines-111
 */

export interface CreateDownloadProcessBody {
    access_token?: string;
    card_ids: number[];
    is_card_type?: boolean;
    is_noun?: boolean;
    uri: string;
}

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/cosphere_media_service/mediafile/views.py/#lines-102
 */

export interface CreateDownloadProcessResponse {
    process_id: string;
}

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/cosphere_media_service/mediafile/views.py/#lines-111
 */

export interface CreateMediaLockBody {
    content_uris: string[];
    fragment_id: number;
}

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/.venv/src/lily/lily/base/serializers.py/#lines-158
 */

export interface CreateMediaLockResponse {}

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/cosphere_media_service/mediafile/views.py/#lines-111
 */

export interface CreateUploadProcessBody {
    card_ids: number[];
    content_type: string;
    is_canvas?: boolean;
    is_card_type?: boolean;
    key: string;
}

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/cosphere_media_service/mediafile/views.py/#lines-102
 */

export interface CreateUploadProcessResponse {
    process_id: string;
}

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/cosphere_media_service/mediafile/views.py/#lines-41
 */

export interface ReadInvariantsQuery {
    access_token?: string;
    uri: string;
}

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/cosphere_media_service/mediafile/invariants.py/#lines-21
 */

export interface ReadInvariantsResponse {
    content_length: number;
    etag: string;
    extension: string;
    host: string;
    last_modified: string;
    normalized_uri: string;
    params: Object;
    type: string;
}

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/cosphere_media_service/mediafile/views.py/#lines-41
 */

export interface ReadProcessStateQuery {
    process_id: string;
    is_canvas?: boolean;
}

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/.venv/src/lily/lily/base/serializers.py/#lines-163
 */

export interface ReadProcessStateResponse {}

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/cosphere_media_service/mediafile/views.py/#lines-41
 */

export interface SignProcessQuery {
    datetime: string;
    to_sign: string;
}

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/.venv/src/lily/lily/base/serializers.py/#lines-158
 */

export interface SignProcessResponse {}

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/cosphere_media_service/mediafile/views.py/#lines-41
 */

export interface WatchConversionStatusQuery {
    access_token?: string;
}

/**
 * https://bitbucket.org/goodai/cosphere-media-service/src/e3b76fc8e495bd20c972adba990a530b504c15c2/.venv/src/lily/lily/base/serializers.py/#lines-158
 */

export interface WatchConversionStatusResponse {}