/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Processes Management Domain Examples
 */

/**
 * Examples for CREATE_DELETION_PROCESS
 */
export const CreateDeletionProcessExamples = {
    "201 (DELETION_PROCESS_CREATED)": {
        "content": {
            "@event": "DELETION_PROCESS_CREATED",
            "@type": "process",
            "process_id": "4378f7e"
        },
        "content_type": "application/json",
        "status": 201
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "content_uris": [
                    "This field is required."
                ]
            },
            "user_id": 8695
        },
        "content_type": "application/json",
        "status": 400
    }
}

/**
 * Examples for CREATE_DOWNLOAD_PROCESS
 */
export const CreateDownloadProcessExamples = {
    "201 (DOWNLOAD_PROCESS_CREATED)": {
        "content": {
            "@event": "DOWNLOAD_PROCESS_CREATED",
            "@type": "process",
            "process_id": "4378f7e"
        },
        "content_type": "application/json",
        "status": 201
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "uri": [
                    "This field is required."
                ]
            },
            "user_id": 8695
        },
        "content_type": "application/json",
        "status": 400
    }
}

/**
 * Examples for CREATE_MEDIA_LOCK
 */
export const CreateMediaLockExamples = {
    "201 (MEDIA_LOCK_CREATED)": {
        "content": {
            "@event": "MEDIA_LOCK_CREATED",
            "@type": "empty"
        },
        "content_type": "application/json",
        "status": 201
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "content_uris": [
                    "This field is required."
                ]
            },
            "user_id": 8695
        },
        "content_type": "application/json",
        "status": 400
    }
}

/**
 * Examples for CREATE_UPLOAD_PROCESS
 */
export const CreateUploadProcessExamples = {
    "201 (UPLOAD_PROCESS_CREATED)": {
        "content": {
            "@event": "UPLOAD_PROCESS_CREATED",
            "@type": "process",
            "process_id": "4378f7e"
        },
        "content_type": "application/json",
        "status": 201
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "key": [
                    "This field is required."
                ]
            },
            "user_id": 8695
        },
        "content_type": "application/json",
        "status": 400
    }
}

/**
 * Examples for READ_INVARIANTS
 */
export const ReadInvariantsExamples = {
    "200 (INVARIANTS_READ)": {
        "content": {
            "@event": "INVARIANTS_READ",
            "@type": "invariants",
            "content_length": 145,
            "etag": null,
            "extension": ".png",
            "host": "PNG",
            "last_modified": null,
            "normalized_uri": "http://hello.world/1.png",
            "params": {},
            "type": "CANVAS"
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "400 (COULD_NOT_READ_INVARIANTS)": {
        "content": {
            "@event": "COULD_NOT_READ_INVARIANTS",
            "@type": "error",
            "uri": "http://non.existant.org/904343.png",
            "user_id": null
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "400 (QUERY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "QUERY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "uri": [
                    "This field is required."
                ]
            },
            "user_id": 6790
        },
        "content_type": "application/json",
        "status": 400
    }
}

/**
 * Examples for READ_PROCESS_STATE
 */
export const ReadProcessStateExamples = {
    "200 (PROCESS_STATE_READ)": {
        "content": {
            "@event": "PROCESS_STATE_READ",
            "@type": "object",
            "id": 89
        },
        "content_type": "application/json",
        "status": 200
    },
    
    "500 (GENERIC_ERROR_OCCURRED)": {
        "content": {
            "@event": "GENERIC_ERROR_OCCURRED",
            "@type": "error",
            "errors": [
                "HTTPConnectionPool(host='localhost', port=11000): Max retries exceeded with url: /mediaitems/by_process/fd78vfv7 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f0b669c5080>: Failed to establish a new connection: [Errno 111] Connection refused',))"
            ],
            "user_id": 8695
        },
        "content_type": "application/json",
        "status": 500
    }
}

/**
 * Examples for SIGN_PROCESS
 */
export const SignProcessExamples = {
    "200": {
        "content": "af52522c5afb83b5348ed06b5fbd0c",
        "content_type": "text/html; charset=utf-8",
        "status": 200
    },
    
    "400 (QUERY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "QUERY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "datetime": [
                    "This field is required."
                ]
            },
            "user_id": 8695
        },
        "content_type": "application/json",
        "status": 400
    }
}

/**
 * Examples for WATCH_CONVERSION_STATUS
 */
export const WatchConversionStatusExamples = {
    "200 (CONVERSION_STATUS_WATCHED)": {
        "content": {
            "@event": "CONVERSION_STATUS_WATCHED",
            "@type": "empty"
        },
        "content_type": "application/json",
        "status": 200
    }
}