/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Attempt Stats Management Domain Examples
 */

/**
 * Examples for BULK_READ_ATTEMPTSTATS
 */
export const BulkReadAttemptstatsExamples = {
    "200 (ATTEMPTSTATS_BULK_READ)": {
        "content": {
            "@event": "ATTEMPTSTATS_BULK_READ",
            "@type": "attempt_stats_list",
            "attempt_stats": [],
            "count": 3
        },
        "content_type": "application/json",
        "status": 200
    }
}

/**
 * Examples for CREATE_ATTEMPTSTAT
 */
export const CreateAttemptstatExamples = {
    "201 (ATTEMPTSTAT_CREATED)": {
        "content": {
            "@event": "ATTEMPTSTAT_CREATED",
            "@type": "attempt_stat",
            "card_id": 1939,
            "created_timestamp": 1526835474.890859,
            "id": 116,
            "states_path": [
                {
                    "reached_via_event": "NEXT_LOADED",
                    "state": "SOURCE",
                    "timestamp": 943894
                },
                {
                    "reached_via_event": "SHOW_ANSWER",
                    "state": "TARGET",
                    "timestamp": 943994
                },
                {
                    "reached_via_event": "RECALL_ATTEMPT",
                    "state": "ATTEMPT",
                    "timestamp": 944994
                },
                {
                    "reached_via_event": "DO_NOT_GET_IT_YET",
                    "state": "NEXT",
                    "timestamp": 943995
                }
            ],
            "successful": false
        },
        "content_type": "application/json",
        "status": 201
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "card_id": [
                    "This field is required."
                ],
                "states_path": [
                    "This field is required."
                ]
            },
            "user_id": 78
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (COULD_NOT_FIND_CARD)": {
        "content": {
            "@event": "COULD_NOT_FIND_CARD",
            "@type": "error",
            "user_id": 78
        },
        "content_type": "application/json",
        "status": 404
    }
}

/**
 * Examples for CREATE_EXTERNAL_ATTEMPT_STAT
 */
export const CreateExternalAttemptStatExamples = {
    "201 (EXTERNAL_ATTEMPT_STAT_CREATED)": {
        "content": {
            "@event": "EXTERNAL_ATTEMPT_STAT_CREATED",
            "@type": "attempt_stat",
            "card_id": 1944,
            "created_timestamp": 1526835475.148646,
            "id": 121,
            "states_path": [
                {
                    "reached_via_event": null,
                    "state": "EXTERNAL_START",
                    "timestamp": 943894
                },
                {
                    "reached_via_event": "DID_WELL",
                    "score": 0.91,
                    "state": "EXTERNAL_STOP",
                    "timestamp": 943994
                },
                {
                    "reached_via_event": null,
                    "state": "EXTERNAL_CLOSE",
                    "timestamp": 946995
                }
            ],
            "successful": true
        },
        "content_type": "application/json",
        "status": 201
    },
    
    "400 (BODY_DID_NOT_VALIDATE)": {
        "content": {
            "@event": "BODY_DID_NOT_VALIDATE",
            "@type": "error",
            "errors": {
                "states_path": [
                    "This field is required."
                ]
            },
            "user_id": 78
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "400 (MISMATCHED_ORIGIN_DETECTED)": {
        "content": {
            "@event": "MISMATCHED_ORIGIN_DETECTED",
            "@type": "error",
            "user_id": 78
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "400 (MISSING_HEADER_DATA_DETECTED)": {
        "content": {
            "@event": "MISSING_HEADER_DATA_DETECTED",
            "@type": "error",
            "user_id": 78
        },
        "content_type": "application/json",
        "status": 400
    },
    
    "404 (COULD_NOT_FIND_CARD)": {
        "content": {
            "@event": "COULD_NOT_FIND_CARD",
            "@type": "error",
            "user_id": 78
        },
        "content_type": "application/json",
        "status": 404
    }
}