/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Attempt Stats Management Domain Examples
 */

/**
 * Examples for BULK_READ_ATTEMPTSTATS
 */
export const BulkReadAttemptstatsExamples = {
    
}

/**
 * Examples for CREATE_ATTEMPTSTAT
 */
export const CreateAttemptstatExamples = {
    
}

/**
 * Examples for CREATE_EXTERNAL_ATTEMPT_STAT
 */
export const CreateExternalAttemptStatExamples = {
    
}