/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Cards Management Domain Examples
 */

/**
 * Examples for BULK_DELETE_CARDS
 */
export const BulkDeleteCardsExamples = {
    
}

/**
 * Examples for BULK_READ_CARDS
 */
export const BulkReadCardsExamples = {
    
}

/**
 * Examples for CREATE_CARD
 */
export const CreateCardExamples = {
    
}

/**
 * Examples for READ_CARD
 */
export const ReadCardExamples = {
    
}

/**
 * Examples for UPDATE_CARD
 */
export const UpdateCardExamples = {
    
}