/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * MediaItems Management Domain Examples
 */

/**
 * Examples for BULK_READ_MEDIAITEMS
 */
export const BulkReadMediaitemsExamples = {
    
}

/**
 * Examples for DELETE_MEDIAITEM
 */
export const DeleteMediaitemExamples = {
    
}

/**
 * Examples for READ_MEDIAITEM
 */
export const ReadMediaitemExamples = {
    
}

/**
 * Examples for READ_MEDIAITEM_BY_PROCESS_ID
 */
export const ReadMediaitemByProcessIdExamples = {
    
}

/**
 * Examples for READ_OR_CREATE_MEDIAITEM
 */
export const ReadOrCreateMediaitemExamples = {
    
}

/**
 * Examples for UPDATE_MEDIAITEM
 */
export const UpdateMediaitemExamples = {
    
}

/**
 * Examples for UPDATE_MEDIAITEM_REPRESENTATION
 */
export const UpdateMediaitemRepresentationExamples = {
    
}