/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Notification Management Domain Examples
 */

/**
 * Examples for ACKNOWLEDGE_NOTIFICATION
 */
export const AcknowledgeNotificationExamples = {
    
}

/**
 * Examples for BULK_READ_NOTIFICATIONS
 */
export const BulkReadNotificationsExamples = {
    
}