/**
  * THIS FILE WILL BE AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

import { Injectable, Injector } from '@angular/core';

@Injectable()
export class APIService {

    constructor(private injector: Injector) {}

}