/**
  * THIS FILE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE
  * OVERWRITTEN
  */

/**
 * Contact Management Domain Models
 */

/**
 * https://bitbucket.org/goodai/cosphere-auth-service/src/09d74e1c1f6871739268cd74315b4f114592af2c/cosphere_auth_service/contact/views.py/#lines-34
 */

export interface CreateAnonymousContactAttemptBody {
    email: string;
    text: string;
}

/**
 * https://bitbucket.org/goodai/cosphere-auth-service/src/09d74e1c1f6871739268cd74315b4f114592af2c/.venv/src/lily/lily/base/serializers.py/#lines-158
 */

export interface CreateAnonymousContactAttemptResponse {}

/**
 * https://bitbucket.org/goodai/cosphere-auth-service/src/09d74e1c1f6871739268cd74315b4f114592af2c/cosphere_auth_service/contact/views.py/#lines-34
 */

export interface SendAuthenticatedContactMessageBody {
    text: string;
}

/**
 * https://bitbucket.org/goodai/cosphere-auth-service/src/09d74e1c1f6871739268cd74315b4f114592af2c/.venv/src/lily/lily/base/serializers.py/#lines-158
 */

export interface SendAuthenticatedContactMessageResponse {}

/**
 * https://bitbucket.org/goodai/cosphere-auth-service/src/09d74e1c1f6871739268cd74315b4f114592af2c/cosphere_auth_service/contact/views.py/#lines-86
 */

export interface VerifyAnonymousContactAttemptBody {
    code: string;
    email: string;
}

/**
 * https://bitbucket.org/goodai/cosphere-auth-service/src/09d74e1c1f6871739268cd74315b4f114592af2c/.venv/src/lily/lily/base/serializers.py/#lines-158
 */

export interface VerifyAnonymousContactAttemptResponse {}